# Generated by Django 5.0.6 on 2024-06-11 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowerapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('propertyLabel', models.CharField(max_length=100)),
                ('propertyValue', models.CharField(max_length=500)),
                ('itemId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flowerapp.item')),
            ],
        ),
    ]
