# Generated by Django 5.0.6 on 2024-06-13 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowerapp', '0002_itemdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='img',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
