# Generated by Django 5.0.6 on 2024-06-14 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowerapp', '0004_alter_item_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='detail1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='detail2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='endTime',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='startTime',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='track',
            name='itemType',
            field=models.CharField(choices=[('EVE', 'Event'), ('SEG', 'Segment'), ('SER', 'Series'), ('PLP', 'Plot Point')], default='SER', max_length=3),
        ),
        migrations.AlterField(
            model_name='item',
            name='end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='start',
            field=models.DateField(),
        ),
    ]
