# Generated by Django 5.0.6 on 2024-06-20 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowerapp', '0006_item_additional_info_delete_itemdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='itemType',
            field=models.CharField(choices=[('EVE', 'Event'), ('SEG', 'Segment'), ('SER', 'Series'), ('TSE', 'TimeSeries')], default='SER', max_length=3),
        ),
        migrations.CreateModel(
            name='TimeSeriesPlotPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('value', models.FloatField()),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flowerapp.track')),
            ],
        ),
    ]
